server:
  tomcat:
    max-connections: 20000 # 커넥션당 시간 제한
    threads:
      max: 600
      min-spare: 100

spring:
  profiles:
    group:
      local: local
      local-dev: local-dev
      dev: dev

    active: local-dev


