spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/tutti_dev
    driver-class-name: com.mysql.cj.jdbc.Driver