spring:
  # .env import
  config:
    import: optional:file:.env[.properties]
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/tutti_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

# JWT
jwt:
  secret: ${JWT_SECRET}

# OAuth
security:
  oauth2:
    client:
      registration:
        google:
          client-name: google
          client-id: ${GOOGLE_CLIENT_ID}
          redirect-uri: ${BASE_URL}/login/oauth2/code/google
          authorization-grant-type: authorization_code
          scope:
            - profile
            - email

        naver:
          client-name: naver
          client-id: ${NAVER_CLIENT_ID}
          client-secret: ${NAVER_CLIENT_SECRET}
          redirect-uri: ${BASE_URL}/members/login/naver
          authorization-grant-type: authorization_code
          scope:
            - name
            - email
    provider:
      naver:
        authorization-uri: https://nid.naver.com/oauth2.0/authorize
        token-uri: https://nid.naver.com/oauth2.0/token
        user-info-uri: https://openapi.naver.com/v1/nid/me
        user-name-attribute: response

# Mail
mail:
  smtp:
    host: smtp.gmail.com
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

# Payment
toss:
  secret-key: ${TOSS_SECRET_KEY}
  cancel-api: https://api.tosspayments.com/v1/payments
  confirm-api: https://api.tosspayments.com/v1/payments/confirm
