spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/tutti_dev
    driver-class-name: com.mysql.cj.jdbc.Driver
api:
  product:
    url: http://1.230.77.225:4796